#! /bin/sh
case "$1" in
    start)
    echo "Drivers-Loading"
    scull_load.sh
    module_load.sh faulty
    modprobe hello.sh
    ;;
    stop)
    echo"Drivers-Unloading"
    scull_unload.sh
    module_unload.sh faulty
    rmmod hello.sh
    ;;
    *)
    echo "Usage $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
